name: aenigma
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.1
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  open_settings: ^2.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/